services:
  - type: web
    name: tradebot
    env: python
    region: oregon  # or ohio, frankfurt, singapore, etc.
    plan: free  # or starter/pro depending on your needs
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # set in Render dashboard (your Telegram bot token)
      - key: HUGGINGFACE_TOKEN
        sync: false  # set in Render dashboard (your HF token)
    pythonVersion: 3.10
    autoDeploy: true
