services:
  - type: web
    name: tradebot
    env: python
    region: oregon  # or choose your nearest region
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel==0.42.0
      pip install torch==2.2.1 --extra-index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.10
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false  # set this manually in the Render dashboard
      - key: HUGGINGFACE_TOKEN
        sync: false  # set this manually too
